plugins {
	id 'java'
	id 'application'
	id 'checkstyle'
	id 'jacoco'
	id 'com.github.spotbugs' version '6.0.18'
	id 'com.diffplug.spotless' version '6.25.0'
}

group = 'ace'
version = '0.0.1-SNAPSHOT'
description = 'job-interview-simulator'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	spotbugsPlugins 'com.h3xstream.findsecbugs:findsecbugs-plugin:1.13.0'

	compileOnly("com.github.spotbugs:spotbugs-annotations:4.9.8")
	testCompileOnly("com.github.spotbugs:spotbugs-annotations:4.9.8")
	spotbugs("com.github.spotbugs:spotbugs-annotations:4.9.8")
	spotbugs("com.github.spotbugs:spotbugs:4.9.8")
	implementation 'org.apache.pdfbox:pdfbox:3.0.2'

	// Lombok pour réduire le boilerplate
	compileOnly 'org.projectlombok:lombok:1.18.30'
	annotationProcessor 'org.projectlombok:lombok:1.18.30'
	testCompileOnly 'org.projectlombok:lombok:1.18.30'
	testAnnotationProcessor 'org.projectlombok:lombok:1.18.30'

	// LangChain4J
	implementation 'dev.langchain4j:langchain4j:1.8.0'
	implementation 'dev.langchain4j:langchain4j-ollama:1.8.0'

	// Test
	testImplementation 'org.mockito:mockito-core:5.14.2'
	testImplementation 'org.mockito:mockito-junit-jupiter:5.14.2'
	testImplementation 'org.junit.jupiter:junit-jupiter:5.11.3'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

	runtimeOnly 'org.slf4j:slf4j-simple:2.0.16'
}

application {
	mainClass = 'ace.projetprogpro.ui.ConsoleUi'
}

configurations.matching { it.name.toLowerCase().contains("spotbugs") }.all {
	resolutionStrategy.force(
			"com.github.spotbugs:spotbugs:4.9.8",
			"com.github.spotbugs:spotbugs-annotations:4.9.8"
	)
	resolutionStrategy.eachDependency {
		if (requested.group == "com.github.spotbugs" && requested.name == "spotbugs") {
			useVersion("4.9.8")
		}
		if (requested.group == "com.github.spotbugs" && requested.name == "spotbugs-annotations") {
			useVersion("4.9.8")
		}
	}
}


checkstyle {
	toolVersion = "10.18.1"
}

spotbugs {
	toolVersion = "4.9.8"
}

spotless {
	java {
		eclipse().configFile('spotless-eclipse.xml')
		target 'src/main/java/**/*.java', 'src/test/java/**/*.java'
		targetExclude '**/build/**'
	}
}

tasks.named('jar') {
	manifest {
		attributes 'Main-Class': 'ace.projetprogpro.ui.ConsoleUi'
	}
}

tasks.withType(com.github.spotbugs.snom.SpotBugsTask).configureEach {
	jvmArgs.set(['-Duser.language=en', '-Duser.country=US'])

	reports {
		html.required.set(true)
		html.outputLocation.set(file("$buildDir/reports/spotbugs/${name}.html"))
		xml.required.set(false)
	}
}

tasks.named('test') {
	useJUnitPlatform()
}

jacocoTestReport {
	dependsOn test

	reports {
		xml.required.set(true)
		csv.required.set(false)
		html.required.set(true)
	}
}

check.dependsOn jacocoTestReport
