services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    healthcheck:
      # utilise le client intégré -> exit 0 quand le daemon répond
      test: ["CMD", "ollama", "list"]
      interval: 10s
      timeout: 5s
      retries: 60
      start_period: 5m

  ollama-pull:
    image: ollama/ollama:latest
    container_name: projet-prog-pro-ollama-pull-1
    depends_on:
      ollama:
        condition: service_healthy
    entrypoint: ["/bin/sh","-lc"]
    command: >
      ollama pull llama3.1:8b &&
      ollama pull mistral &&
      sleep infinity
    volumes:
      - ollama:/root/.ollama
    restart: "no"

volumes:
  ollama:
